### ISSUE TITLE
FaceTrackPOC not work in tracking mode

### ISSUE THREAD

**Issue by wsAndy** [Project-Babble/ProjectBabble#65]
I use the source code version v 2.0.6-alpha.

Babble is tracking my face and I could get the output value from `babble_processor.py`. but the unity demo seems not work correctly.

![image](https://github.com/user-attachments/assets/2e3a1bb5-b612-442d-861b-2c35fe98767e)

**Comment by RamesTheGeneric** [comment]
Have you set the output multiplier to 100? The unity demo requires the babble app to be set to that as the demo does not multiply the values by default.

**Comment by wsAndy** [comment]
Yes, I have set multipilier to 100 in GUI. 
![image](https://github.com/user-attachments/assets/a5338f66-08bd-4850-9465-c4ca8aecbdbf)

**Comment by wsAndy** [comment]
I only open BabbleApp and unity demo, without vrcft.

**Comment by wsAndy** [comment]
Here is the settings
![image](https://github.com/user-attachments/assets/7f59cea6-341b-401d-b6e8-18e0ef17bb89)

**Comment by RamesTheGeneric** [comment]
Oh, that is the old demo, I believe the send port needs to be set to 9000.

**Comment by RamesTheGeneric** [comment]
I should also add that the model in the repo is very outdated and may not perform well.

**Comment by wsAndy** [comment]
Thanks！When  I change the port to 9000, it works
![image](https://github.com/user-attachments/assets/df065d62-5405-4832-b110-994da0419a3d)

**Comment by wsAndy** [comment]
> I should also add that the model in the repo is very outdated and may not perform well. A replacement is being tested.

Could you please share the latest model?
