### ISSUE TITLE
Docs page is broken/down

### ISSUE THREAD

**Issue by The-Wrench** [Project-Babble/ProjectBabble#67]
Docusaurus broke the website (everypage shows up as a 404 page not found) 
![grafik](https://github.com/user-attachments/assets/361d0649-723c-42d4-be21-2f0413b4960c)

**Comment by u-Kotovsky** [comment]
Same.

**Comment by SummerSigh** [comment]
we've fixed the docs. someone labeled all the png extensions as ".PNG" not ".png" breaking the build because it couldn't reference the images
